### ISSUE TITLE
apply custom scale marks on prices on price-axis

### ISSUE THREAD

**Issue by Alphafivetl** [tradingview/charting-library-tutorial#8] opened 2020-07-10 03:46 UTC
![Screenshot (19)](https://user-images.githubusercontent.com/57444318/87114057-47dc0400-c28d-11ea-8db9-4a675aa0285a.png)
`    
```
defaultChartProps = {
    interval: '15',
    containerId: 'tv_chart_container',
    libraryPath: '/trade/charting_library/',
    chartsStorageUrl: 'https://saveload.tradingview.com',
    chartsStorageApiVersion: '1.1',
    clientId: 'tradingview.com',
    userId: 'public_user_id',
    fullscreen: false,
    autosize: true,
  };

const widgetOptions = {
      debug: false,
      symbol: this.getCurrInstrument(),
      datafeed: this.dataFeed,
      interval: this.defaultChartProps.interval,
      container_id: this.defaultChartProps.containerId,
      library_path: this.defaultChartProps.libraryPath,
      locale: 'en',
      disabled_features: [
        'use_localstorage_for_settings',
        'header_symbol_search',
      ],
      enabled_features: ['study_templates'],
      charts_storage_url: this.defaultChartProps.chartsStorageUrl,
      charts_storage_api_version: this.defaultChartProps
        .chartsStorageApiVersion,
      client_id: this.defaultChartProps.clientId,
      user_id: this.defaultChartProps.userId,
      fullscreen: this.defaultChartProps.fullscreen,
      autosize: this.defaultChartProps.autosize,
      studies_overrides: this.defaultChartProps.studiesOverrides,
      overrides: {
        // "mainSeriesProperties.showCountdown": true,
        'paneProperties.background': '#000000',
        'paneProperties.vertGridProperties.color': '#363c4e',
        'paneProperties.horzGridProperties.color': '#363c4e',
        'symbolWatermarkProperties.transparency': 90,
        'scalesProperties.textColor': '#AAA',
        'mainSeriesProperties.candleStyle.wickUpColor': '#336854',
        'mainSeriesProperties.candleStyle.wickDownColor': '#7f323f',
      },
      custom_css_url: './gray-chart-theme.css',
    };
`
```

i have a pricescale of 100 and minmov 1,,,

i want price axis to have marks on 5 dollars price gap...

am i supposed to provide pass some special property to show the prices on price scale ?

**Comment by eugene-korobko** [comment] 2020-07-10 07:50
Hello!

Unfortunately, this is impossible, charting library calculates price marks automatically based on symbolinfo

**Comment by timocov** [comment] 2020-07-10 08:41
Duplicate of https://github.com/tradingview/charting_library/issues/5119

**Closed by timocov** 2020-07-10 08:41 UTC
