### ISSUE TITLE
How I can enable the Bar Replay Function?

### ISSUE THREAD

**Issue by azataiot** [tradingview/charting-library-tutorial#65] opened 2022-05-18 18:52 UTC
How I can enable the Bar Replay Function, that is on the TV chart by default? 
![CleanShot 2022-05-18 at 21 52 17](https://user-images.githubusercontent.com/8280770/169128112-f90f9cf6-7210-4a60-b7c6-07bc1659d6fe.png)

**Comment by romfrancois** [comment] 2022-05-20 15:15
This is a duplicate of https://github.com/tradingview/charting_library/issues/4777

**Closed** 2022-05-20 15:15 UTC

**Comment by azataiot** [comment] 2022-05-24 10:41
> This is a duplicate of [4777](4777).

Issue 4777 dose not exists ? (404)

**Comment by romfrancois** [comment] 2022-05-24 10:43
Apologies link was badly formatted. Here's the working [one](https://github.com/tradingview/charting_library/issues/4777).
