### ISSUE TITLE
can't able to click on other resolution 

### ISSUE THREAD

**Issue by shubhamsharma1996** [tradingview/charting-library-tutorial#70] opened 2022-10-03 10:50 UTC
![Screenshot from 2022-10-03 16-18-39](https://user-images.githubusercontent.com/52203830/193559829-a2feb105-2512-4da9-bfdb-73ed59a3642c.png)
only hour and day button are clickable in supported resolution why,please help @w0rse  @zaretskysa  @rav3n  @subzey  @kirchet

**Comment by romfrancois** [comment] 2022-10-07 09:53
Hi @shubhamsharma1996 !

Could you please provide more details such as your datafeed configuration which is used to create the resolution dropdown?
It's more important to give us as many info as possible vs directly tagging ppl who would eventually ask the same questions :)

**Comment by serhatopcu** [comment] 2023-06-15 07:55
Hello,
I will try to answer as far as I know. You can't reach all resolutions because you are getting data by using cryptocompare websocket, you can see this in streaming.js where the line "wss://streamer.cryptocompare.com", you need to pay for all resolutions, but cryptocompare is not only option to get data from, for example i am getting minute resolution data from binance websocket for free.

**Comment by romfrancois** [comment] 2023-06-15 11:36
Duplicate of [318](https://github.com/tradingview/charting-library-examples/issues/318#issuecomment-1592749825)

**Closed by romfrancois** 2023-06-15 11:36 UTC
