### ISSUE TITLE
Is the heatmap is available in this library? https://in.tradingview.com/advanced-charts/

### ISSUE THREAD

**Issue by yashashri0809** [tradingview/charting-library-tutorial#128] opened 2024-09-28 09:43 UTC

**Comment by romfrancois** [comment] 2024-09-30 05:55
Duplicate of [8826](https://github.com/tradingview/charting_library/issues/8826)

**Closed by romfrancois** 2024-09-30 05:55 UTC

**Comment by yashashri0809** [comment] 2024-09-30 07:55
It is showing like this:
<img width="960" alt="not access" src="https://github.com/user-attachments/assets/39f8aa64-7995-45bf-bab7-d11741b604ab">

**Comment by yashashri0809** [comment] 2024-09-30 09:39
If I want that then what should I do?

**Comment by romfrancois** [comment] 2024-09-30 09:43
I'm afraid there isn't anything to be done here.
